# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy_helper', '0002_auto_20180720_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='please add a description'),
            preserve_default=False,
        ),
    ]
