# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy_helper', '0003_auto_20180720_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='added_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_jobs', to='handy_helper.User'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to='handy_helper.User'),
        ),
    ]
